### ISSUE TITLE
No email is received

### ISSUE THREAD

**Issue by ACANCAM** [francoisjacquet/rosariosis-module-email#1]
Hello:

I love RosarioSIS, but the internal messaging service is a problem since users have to enter the program to see if they have any messages.

Seeing that you have made a module for sending emails and it seems a good solution. I followed the steps indicated in the installation and everything seems perfect. At the end a message appears saying that the mail has been sent and that I have been successful, but no mail arrives. Nothing is sent and I do not know how to fix it. Can you help me?

Thank you very much

**Comment by francoisjacquet** [comment]
Hello @ACANCAM

Thank you for reporting your issue with email sending.

By the way, having email notifications would be a good enhancement to the Messaging module.

Please post your server OS and configuration.

**Comment by ACANCAM** [comment]
Hello François:

I installed the RosarioSIS in a Google Cloud Platform virtual machine.
The instance runs with Ubuntu 14.04 LTS, Apache 2.4.18, Postgres 9.3.10 and PHP 5.5.9

I've noticed that, when I send an email, although on the page it appears as "success", if I click on the diskette icon it downloads an excell sheet called "send_email.xls" in which it appears as a failed delivery.

I have also noticed that on the login page to the application, if I go to "password help" no password recovery email is sent

My instalation is in www.fundaciondoctrinacristiana.org

Thank you


2017-11-28 21:35 GMT+01:00 François Jacquet <notifications@github.com>:

**Comment by ACANCAM** [comment]
Hello again:

I have found a solution. I do not know if it's the right way, but it works! 

Here you have the link   http://www.forosdelweb.com/f41/ubuntu-lamp-server-funcion-php-mail-como-enviar-emails-1108644/

**Comment by francoisjacquet** [comment]
Hello @ACANCAM

Good to know you were able to install `sendmail` on your server.

As stated in the [INSTALL.md](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md#activate-php-mail-function), sendmail is the only program required to enable email sending on Gnu/Linux servers.
